# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sprocket
version:      0.05
version_from: lib/Sprocket.pm
installdirs:  site
requires:
    Carp:                          
    Class::Accessor::Fast:         
    POE:                           0.3502
    POE::Component::Client::DNS:   
    Scalar::Util:                  
    Time::HiRes:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
